name: Java CI and CD Pipeline with Maven

# Triggers the workflow on code pushes to the cicd-workflow branch and on pull requests targeting the cicd-workflow branch
on:
  push:
    branches: [ "cicd-workflow" ]
  pull_request:
    branches: [ "cicd-workflow" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK ${{matrix.java}}
      uses: actions/setup-java@v4
      with:
        java-version: ${{matrix.java}}
        distribution: 'adopt'
        cache: maven

    - name: Cache Maven packages
      uses: actions/cache@v4 # Caches Maven dependencies to speed up subsequent builds
      with:
        path: ~/.m2 # default location where Maven stores downloaded dependencies
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }} # cache key is used to identify the cached data
        restore-keys: ${{ runner.os }}-m2 # fallback cache keys to restore a more general cache, if the pom.xml files have changed, but the OS and maven locations have not

    - name: Build with Maven Wrapper # Builds the Java application using Maven wrapper mvnw
      run: ./mvnw -B verify
    - name: Run Unit Tests # Runs the unit tests
      run: ./mvnw test
    