name: SSH Test!

on:
  push:
    branches: [ "cicd-workflow" ]
  workflow_dispatch:

jobs:
  ssh-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:

        - name: Set up SSH
          uses: webfactory/ssh-agent@v0.9.0
          with:
            ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

        - run: echo "Hi there!" > my-file

        - name: Copy my-file to EC2
          run: scp -o StrictHostKeyChecking=no my-file ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/

        - name: print diogo from ec2
          run: ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "cat my-file"

        - name: Start Java App Spring PetClinic on EC2 instance
          # Restart the java app on EC2 and redirect both standard output and standard error from the Java application to the app.log file and runs the application in the background
          run: |
                ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "nohup java -jar /home/ubuntu/spring-petclinic-*.jar > app.log 2>&1 &"
