name: SSH Test!

on:
  push:
    branches: [ "cicd-workflow" ]
  workflow_dispatch:

jobs:
  ssh-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:

        - name: Set up SSH
          uses: webfactory/ssh-agent@v0.9.0
          with:
            ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

        - name: Test SSH Connection
          run: ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "echo 'SSH connection successful'"
      
        - name: Deploy JAR to EC2 server
          run: scp -o StrictHostKeyChecking=no target/spring-petclinic-*.jar ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/
       
        - name: Start Java App Spring PetClinic on EC2 instance
          # Restart the java app on EC2 and redirect both standard output and standard error from the Java application to the app.log file and runs the application in the background
          run: ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "nohup java -jar /home/ubuntu/spring-petclinic-*.jar &"  
